# Generated by Django 2.2.19 on 2023-01-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20230124_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-like_date'], 'verbose_name': 'Post Like', 'verbose_name_plural': 'Post Likes'},
        ),
    ]
