# Generated by Django 3.2 on 2023-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_auto_20230125_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
