# Generated by Django 2.2.19 on 2023-01-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
