# Generated by Django 2.2.19 on 2023-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_like_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
