# Generated by Django 2.2.19 on 2023-01-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20230121_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
