# Generated by Django 2.2.19 on 2023-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, help_text='Введите заголовок поста', max_length=200, verbose_name='Заголовок поста'),
            preserve_default=False,
        ),
    ]
