# Generated by Django 2.2.19 on 2023-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Введите заголовок поста', max_length=200, null=True, verbose_name='Заголовок поста'),
        ),
    ]
